//! The profiles under `profiles/`, compiled in: `--techniques h3/rtx5090_sol`
//! works in the runtime image without the repo, and every shipped profile
//! is parsed by the tests.

/// `(name, TOML)`; the name is the path under `profiles/` without `.toml`.
pub static PROFILES: &[(&str, &str)] = &[
    (
        "h3/rtx5090_dense",
        include_str!("../../../../profiles/h3/rtx5090_dense.toml"),
    ),
    (
        "h3/rtx5090_sol",
        include_str!("../../../../profiles/h3/rtx5090_sol.toml"),
    ),
    (
        "h3/rtx5090_fullopt",
        include_str!("../../../../profiles/h3/rtx5090_fullopt.toml"),
    ),
    (
        "h3/rtx5090_fullopt_taeh3",
        include_str!("../../../../profiles/h3/rtx5090_fullopt_taeh3.toml"),
    ),
    (
        "h3/fasth3_8step",
        include_str!("../../../../profiles/h3/fasth3_8step.toml"),
    ),
    (
        "h3/fasth3_4step_vsa",
        include_str!("../../../../profiles/h3/fasth3_4step_vsa.toml"),
    ),
    (
        "h3/fasth3_4step_dense",
        include_str!("../../../../profiles/h3/fasth3_4step_dense.toml"),
    ),
    (
        "h3/sol_h3_4step",
        include_str!("../../../../profiles/h3/sol_h3_4step.toml"),
    ),
    (
        "h3/sol_h3_4step_engine",
        include_str!("../../../../profiles/h3/sol_h3_4step_engine.toml"),
    ),
    (
        "h3/fasth3_8step_sol",
        include_str!("../../../../profiles/h3/fasth3_8step_sol.toml"),
    ),
    (
        "h3/fasth3_8step_teacache",
        include_str!("../../../../profiles/h3/fasth3_8step_teacache.toml"),
    ),
    (
        "h3/fasth3_8step_sol_teacache",
        include_str!("../../../../profiles/h3/fasth3_8step_sol_teacache.toml"),
    ),
    (
        "h3/fasth3_8step_vsa085",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa085.toml"),
    ),
    (
        "h3/fasth3_8step_vsa09",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa09.toml"),
    ),
    (
        "h3/fasth3_8step_vsa0925",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa0925.toml"),
    ),
    (
        "h3/fasth3_8step_vsa095",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa095.toml"),
    ),
    (
        "h3/fasth3_8step_vsa09_edges",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa09_edges.toml"),
    ),
    (
        "h3/fasth3_8step_vsa095_edges",
        include_str!("../../../../profiles/h3/fasth3_8step_vsa095_edges.toml"),
    ),
    (
        "h3/fasth3_8step_sol_vsa_d2",
        include_str!("../../../../profiles/h3/fasth3_8step_sol_vsa_d2.toml"),
    ),
    (
        "h3/fasth3_8step_sol_vsa_d2_t05",
        include_str!("../../../../profiles/h3/fasth3_8step_sol_vsa_d2_t05.toml"),
    ),
    (
        "h3/fasth3_8step_sol_d2",
        include_str!("../../../../profiles/h3/fasth3_8step_sol_d2.toml"),
    ),
    (
        "h3/fasth3_8step_fp8attn",
        include_str!("../../../../profiles/h3/fasth3_8step_fp8attn.toml"),
    ),
    (
        "h3/fasth3_4step_vsa0925",
        include_str!("../../../../profiles/h3/fasth3_4step_vsa0925.toml"),
    ),
    (
        "h3/fasth3_4step_vsa095",
        include_str!("../../../../profiles/h3/fasth3_4step_vsa095.toml"),
    ),
    (
        "h3/fasth3_4step_vsa095_edges",
        include_str!("../../../../profiles/h3/fasth3_4step_vsa095_edges.toml"),
    ),
    (
        "h3/fasth3_4step_vsa_fp8attn",
        include_str!("../../../../profiles/h3/fasth3_4step_vsa_fp8attn.toml"),
    ),
    (
        "h3/sol_h3_4step_engine_t075",
        include_str!("../../../../profiles/h3/sol_h3_4step_engine_t075.toml"),
    ),
    (
        "h3/sol_h3_4step_engine_ladder",
        include_str!("../../../../profiles/h3/sol_h3_4step_engine_ladder.toml"),
    ),
    (
        "h3/sol_h3_4step_fp8attn",
        include_str!("../../../../profiles/h3/sol_h3_4step_fp8attn.toml"),
    ),
    (
        "h3/rtx5090_fullopt_d6",
        include_str!("../../../../profiles/h3/rtx5090_fullopt_d6.toml"),
    ),
    (
        "h3/rtx5090_fullopt_t125",
        include_str!("../../../../profiles/h3/rtx5090_fullopt_t125.toml"),
    ),
    (
        "h3/rtx5090_fullopt_fp8attn",
        include_str!("../../../../profiles/h3/rtx5090_fullopt_fp8attn.toml"),
    ),
    (
        "ltx2/ltx25_rtx5090_distill_bf16",
        include_str!("../../../../profiles/ltx2/ltx25_rtx5090_distill_bf16.toml"),
    ),
    (
        "ltx2/ltx25_distill_sol",
        include_str!("../../../../profiles/ltx2/ltx25_distill_sol.toml"),
    ),
    (
        "ltx2/ltx25_distill_dense",
        include_str!("../../../../profiles/ltx2/ltx25_distill_dense.toml"),
    ),
    (
        "ltx2/ltx25_distill_sol_taehv",
        include_str!("../../../../profiles/ltx2/ltx25_distill_sol_taehv.toml"),
    ),
    (
        "ltx2/ltx25_distill_sol_fp8",
        include_str!("../../../../profiles/ltx2/ltx25_distill_sol_fp8.toml"),
    ),
];

/// A builtin profile by name (`h3/rtx5090_sol`, with or without `.toml` or
/// a leading `profiles/`).
pub fn get(name: &str) -> Option<&'static str> {
    let key = name
        .trim_start_matches("./")
        .trim_start_matches("profiles/")
        .trim_end_matches(".toml");
    PROFILES.iter().find(|(n, _)| *n == key).map(|(_, t)| *t)
}

pub fn names() -> Vec<&'static str> {
    PROFILES.iter().map(|(n, _)| *n).collect()
}
