// Generated by control/gen-configs.mjs from scripts/gpu/weights-manifest.tsv and
// weights-revisions.tsv: do not edit; edit the TSVs and run `node gen-configs.mjs`.
// The weight trees a GMI / Brev pod can fetch from the Hub at boot (weights_source
// hub, docs/serve/deploy-gmi-brev.md §7): one repo each, at a pinned revision.
export interface HubTree {
  repo: string;
  revision: string;
  globs: string[];
}
export const HUB_TREES: Record<string, HubTree> = {
  "h3-8step": { repo: "FastVideo/FastVideo-FastH3-8-Step-V2", revision: "3da2ddfe1954d9cda4c05b643dc0f26007a655c5", globs: ["tokenizer/*","text_encoder/*.json","text_encoder/model-0000[1-9]-of-00014.safetensors","text_encoder/model-0001[01]-of-00014.safetensors","text_encoder/model-0001[2-4]-of-00014.safetensors","transformer/*","audio_vae/*","vae/*"] },
  "h3-base": { repo: "MiniMaxAI/MiniMax-H3", revision: "42ed227ee7df40d41602854ae760620d6eb651fe", globs: ["tokenizer/*","text_encoder/*.json","text_encoder/model-0000[1-9]-of-00014.safetensors","text_encoder/model-0001[01]-of-00014.safetensors","text_encoder/model-0001[2-4]-of-00014.safetensors","transformer/*","audio_vae/*","vae/*"] },
  "FastH3-4-step-Preview-v1-LoRA": { repo: "FastVideo/FastVideo-FastH3-4-step-Preview-v1-LoRA", revision: "f509e629374cac104e7f62daecce6d1488a3041d", globs: ["dense-datafree/adapter_model.safetensors","vsa-datafree/adapter_model.safetensors"] },
  "upscaler": { repo: "LBH-123-AI/Minimax_h3_latent_Upscaler", revision: "3f941d5d182014dd5c0a5e16330420ee2d4aa0c6", globs: ["minimax_h3_latent_upscaler_3d_conv_v1/minimax_h3_latent_upscaler_3d_conv_v1_bf16.safetensors"] },
  "h3-to-ltx": { repo: "Efficient-Large-Model/H3-to-LTX-Latent-Adapter", revision: "1792c42689a0f22de880eaf57a187c6a373a636d", globs: ["config.json","model.safetensors"] },
  "ltx2": { repo: "Lightricks/LTX-2", revision: "dfcc2108383fe1aaa0584bdf55d368a4bdadd90c", globs: ["tokenizer/*","text_encoder/model-*","text_encoder/*.json","vae/*","audio_vae/*","vocoder/*","ltx-2-19b-distilled.safetensors"] },
  "ltx25": { repo: "Lightricks/LTX-2.5-Diffusers", revision: "426936f8b22dc28e4def61e515478b0b7e4a53cc", globs: ["tokenizer/*","text_encoder/model-*","text_encoder/*.json","connectors/*","transformer/*","vae/*","audio_vae/*","vocoder/*","latent_upsampler/*","ltx-2.5-22b-distilled-lora-450-bf16.safetensors"] },
  "ltx23": { repo: "FastVideo/LTX-2.3-Distilled-Diffusers", revision: "22b09fb1860a944bf10fa21f033d957d9ab9ec20", globs: ["tokenizer/*","text_encoder/model-*","text_encoder/gemma/*","text_encoder/*.json","text_embedding_projection/*","transformer/*","vae/*","audio_vae/*","vocoder/*","spatial_upscaler/*","latent_upsampler/*","ltx-2.3-22b-distilled-lora-384-1.1.safetensors","ltx-2.3-22b-distilled-lora-384.safetensors"] },
  "ltx25-dev": { repo: "Lightricks/LTX-2.5-Diffusers", revision: "426936f8b22dc28e4def61e515478b0b7e4a53cc", globs: ["transformer_full/*"] },
  "ltx25-ic-lora-ingredients": { repo: "Lightricks/LTX-2.5-22b-IC-LoRA-Ingredients", revision: "12040e4091ac2008d3906a594e31a7fb1ab9d546", globs: ["ltx-2.5-22b-ic-lora-ingredients-0.9.safetensors","README.md"] },
  "hy15-480-t2v": { repo: "hunyuanvideo-community/HunyuanVideo-1.5-Diffusers-480p_t2v", revision: "286be7ce72277246578a3e3cc2487e95ddae5bcf", globs: ["tokenizer/*","tokenizer_2/*","text_encoder/*","text_encoder_2/*","transformer/*","vae/*","scheduler/*"] },
  "hy15-480-i2v": { repo: "hunyuanvideo-community/HunyuanVideo-1.5-Diffusers-480p_i2v_step_distilled", revision: "854c04a4c8a53d990b418c7478f0802c0fc8c726", globs: ["tokenizer/*","tokenizer_2/*","text_encoder/*","text_encoder_2/*","transformer/*","vae/*","scheduler/*"] },
  "hy15-720-t2v": { repo: "hunyuanvideo-community/HunyuanVideo-1.5-Diffusers-720p_t2v", revision: "f4dbc4a1efa4ac8ea56680cdf79d9f455105e814", globs: ["tokenizer/*","tokenizer_2/*","text_encoder/*","text_encoder_2/*","transformer/*","vae/*","scheduler/*"] },
  "hy15-720-i2v": { repo: "hunyuanvideo-community/HunyuanVideo-1.5-Diffusers-720p_i2v_distilled", revision: "a1d10cf3af7978bf090b0ab3d8cd79b143444e23", globs: ["tokenizer/*","tokenizer_2/*","text_encoder/*","text_encoder_2/*","transformer/*","vae/*","scheduler/*"] },
  "fastwan21-1.3b": { repo: "FastVideo/FastWan2.1-T2V-1.3B-Diffusers", revision: "25e7ed7f41fd8ce2fdd108688c65e8caf0ce3aef", globs: ["transformer/*","tokenizer/*","text_encoder/*","vae/*"] },
  "wan22-ti2v-5b": { repo: "Wan-AI/Wan2.2-TI2V-5B-Diffusers", revision: "b8fff7315c768468a5333511427288870b2e9635", globs: ["scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "fastwan22-ti2v-5b": { repo: "FastVideo/FastWan2.2-TI2V-5B-FullAttn-Diffusers", revision: "3e187042a324f6f5fb68fd22110a78725253de8f", globs: ["scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "wan21-t2v-14b": { repo: "Wan-AI/Wan2.1-T2V-14B-Diffusers", revision: "38ec498cb3208fb688890f8cc7e94ede2cbd7f68", globs: ["scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "sfwan21-1.3b": { repo: "wlsaidhi/SFWan2.1-T2V-1.3B-Diffusers", revision: "4b44356635ae5e927ca552a220f768022be76004", globs: ["scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "sana-video-2b-480p": { repo: "Efficient-Large-Model/SANA-Video_2B_480p_diffusers", revision: "db5f398b13ca086d09a50ce156c20527773841b1", globs: ["model_index.json","scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "auxiliary/upscalers/seedvr2": { repo: "numz/SeedVR2_comfyUI", revision: "09ced71023636e9bc8cdf9cdecfb2625d1e691e8", globs: ["seedvr2_ema_3b_fp16.safetensors","ema_vae_fp16.safetensors"] },
  "auxiliary/upscalers/flashvsr-v1.1": { repo: "JunhaoZhuang/FlashVSR-v1.1", revision: "27561b186ded3402d7c975f4fd722e2885b6135f", globs: ["diffusion_pytorch_model_streaming_dmd.safetensors","LQ_proj_in.ckpt","TCDecoder.ckpt","Wan2.1_VAE.pth","config.json"] },
  "longlive-1.3b": { repo: "Efficient-Large-Model/LongLive-1.3B", revision: "cda9138d93872ef109d9a74c270184eb3a5acc6e", globs: ["README.md","models/longlive_base.pt","models/lora.pt","prompts/interactive_example.jsonl"] },
  "longlive2-5b": { repo: "Efficient-Large-Model/LongLive-2.0-5B", revision: "8521079b863720a57c1a8d9b19c8d9e6ccb04c0f", globs: ["README.md","model_bf16.pt"] },
  "longlive2-5b-nvfp4-s4": { repo: "Efficient-Large-Model/LongLive-2.0-5B-NVFP4-S4", revision: "427ffb75f0a3ae82714cd4b3aaa7463839da38a7", globs: ["README.md","model_4o6.pt"] },
  "longlive2-5b-nvfp4-s2": { repo: "Efficient-Large-Model/LongLive-2.0-5B-NVFP4-S2", revision: "9ab6c9c70db97e1994d87bca3b8c4ed31e5b62e2", globs: ["README.md","model_4o6.pt"] },
  "longlive-plug/minimax-h3-few-step": { repo: "Efficient-Large-Model/LongLive-Plug-MiniMax-H3-few-step", revision: "b3686f432d3f20d6d6462a91d4c09ba7f189c0a2", globs: ["*"] },
  "longlive-plug/minimax-h3-cfg": { repo: "Efficient-Large-Model/LongLive-Plug-MiniMax-H3-cfg", revision: "de1f4e8c7310917a7bf0417ff041abb8bb7b0927", globs: ["*.json","*.md","LICENSE","NOTICE","SHA256SUMS.txt","adapter_model.safetensors"] },
  "longlive-plug/wan21-t2v-14b-few-step": { repo: "Efficient-Large-Model/LongLive-Plug-Wan2.1-T2V-14B-few-step", revision: "f125af0533b94e2cee0163a7a42bb736d59a1d37", globs: ["README.md","export_generator_lora.py","generator_lora_lightx2v.safetensors","inference_config.json","provenance.json"] },
  "longlive-plug/wan21-t2v-14b-cfg": { repo: "Efficient-Large-Model/LongLive-Plug-Wan2.1-T2V-14B-cfg", revision: "32b8aa3d1db3d178a9c82f3731cc917a34fb7693", globs: ["README.md","SHA256SUMS","adapter_config.json","adapter_model.safetensors","inference_overrides.yaml","provenance.json","release_metadata.json","training_config.yaml"] },
  "longlive-plug/wan22-ti2v-5b-few-step": { repo: "Efficient-Large-Model/LongLive-Plug-Wan2.2-TI2V-5B-few-step", revision: "38a6ec4e8f5b644749d3072bfe1ac383d00951c0", globs: ["README.md","adapter_config.json","adapter_model.safetensors","inference_config.yaml","load_generator_lora.py","provenance.json","training_config.yaml"] },
  "longlive-plug/wan22-ti2v-5b-cfg": { repo: "Efficient-Large-Model/LongLive-Plug-Wan2.2-TI2V-5B-cfg", revision: "fa1f9280778aa27c8038fe06e29fb5f2ed6be451", globs: ["README.md","SHA256SUMS","adapter_config.json","adapter_model.safetensors","inference_overrides.yaml","provenance.json","release_metadata.json","training_config.yaml"] },
  "wan21-t2v-1.3b": { repo: "Wan-AI/Wan2.1-T2V-1.3B-Diffusers", revision: "0fad780a534b6463e45facd96134c9f345acfa5b", globs: ["model_index.json","scheduler/*","tokenizer/*","text_encoder/*","transformer/*","vae/*"] },
  "ltx23-dev": { repo: "Lightricks/LTX-2.3", revision: "3c6a4e66e5d0a684231950b9c74dd4ded7b6fadc", globs: ["ltx-2.3-22b-dev.safetensors","ltx-2.3-22b-distilled-lora-384-1.1.safetensors","ltx-2.3-spatial-upscaler-x2-1.1.safetensors"] },
  "wan22-t2v-a14b": { repo: "Wan-AI/Wan2.2-T2V-A14B-Diffusers", revision: "5be7df9619b54f4e2667b2755bc6a756675b5cd7", globs: ["model_index.json","scheduler/*","tokenizer/*","text_encoder/*","transformer/*","transformer_2/*","vae/*"] },
  "lingbot-video-moe-30b-a3b": { repo: "robbyant/lingbot-video-moe-30b-a3b", revision: "f2e538f64afe00cc4ae674db2aeb52e2945edfd5", globs: ["model_index.json","scheduler/*","transformer/*","refiner/*","text_encoder/*","processor/*","vae/*"] },
  "cosmos3-super": { repo: "nvidia/Cosmos3-Super", revision: "f543c56225b2e04d0ad141e29655be3a45d9c455", globs: ["model_index.json","scheduler/*","transformer/*","vae/*","text_tokenizer/*"] },
};
/** auxiliary/ files: a pinned URL, its SHA-256 and size (verify-weights.sh aux). */
export const AUX_FILES: { path: string; url: string; sha256: string; size: number }[] = [
  { path: "auxiliary/tae/taeh3.safetensors", url: "https://raw.githubusercontent.com/madebyollin/taehv/e589fddc076e77f5ba8cd6baabe4ba3260b261cd/safetensors/taeh3.safetensors", sha256: "4fd022bfcab08772fe0536b17ea1a3bbb5625be11e397868d1c5d891863d4c13", size: 22709752 },
  { path: "auxiliary/tae/taeltx2_3_wide.safetensors", url: "https://raw.githubusercontent.com/madebyollin/taehv/32ac0146b11007cda5a57b60a3b35653361fb8a4/safetensors/taeltx2_3_wide.safetensors", sha256: "0a69291425015e8eb4309028e7de1d17d2a11f58ba88e0120453bc36f352e082", size: 60359856 },
  { path: "auxiliary/tae/taew2_1.safetensors", url: "https://raw.githubusercontent.com/madebyollin/taehv/e589fddc076e77f5ba8cd6baabe4ba3260b261cd/safetensors/taew2_1.safetensors", sha256: "04766eac0221b5390b985ae3fdcca652cbb4b1e8b82b28ea7ff89dfad1b1a93f", size: 22642902 },
  { path: "auxiliary/tae/taew2_2.safetensors", url: "https://raw.githubusercontent.com/madebyollin/taehv/e589fddc076e77f5ba8cd6baabe4ba3260b261cd/safetensors/taew2_2.safetensors", sha256: "b84609b2a133d48434bd9636bfcb44bf05168dc436e2d3cecf26256faa1f5325", size: 22848048 },
  { path: "auxiliary/lpips/alexnet-owt-7be5be79.pth", url: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth", sha256: "7be5be791159472b1fbf3c69796f7cb30dca7ad8466c2df70058c37116cdee02", size: 244408911 },
  { path: "auxiliary/lpips/lpips_v0.1_alex.pth", url: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/082bb24f84c091ea94de2867d34c4544f68e0963/lpips/weights/v0.1/alex.pth", sha256: "df73285e35b22355a2df87cdb6b70b343713b667eddbda73e1977e0c860835c0", size: 6009 },
];
