//! SF-Wan causal block backend (WP-15, design §5.4) over E6's
//! `wan::stream::CausalRollout`.
//!
//! - [`CausalDriver`]: the three `causal_*` methods of [`EngineBackend`] for
//!   one resident causal Wan pipeline. The full `CudaBackend` (WP-11)
//!   delegates its causal calls here; the driver owns the per-session
//!   rollouts (KV cache, TAEHV decode state, prompt embedding).
//! - [`CausalCudaBackend`]: a backend that serves only SF-Wan, so causal
//!   streaming runs on a GPU before (or without) the batch backend
//!   (`FV_SFWAN_WEIGHTS`, see [`CausalCudaBackend::from_env`]).
//!
//! Per executor turn: apply a reset (with the block's seed) or a prompt
//! change (encoded now, applied from this block: the rollout keeps the KV
//! cache, `PromptSwitch::Keep`), then denoise + decode one block and hand
//! its RGB8 frames to the sink. The engine cancel token is bridged to the
//! pipeline hooks, so closing a session interrupts the block at the next
//! denoise step; a cancelled block is regenerated by the next call.
//!
//! The pipeline is leaked to `'static` on load: a rollout borrows it for the
//! session's lifetime and the SF-Wan model stays resident for the process
//! (swap mode never unloads a causal model).

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::atomic::Ordering;

use fastvideo_cudarc::hooks::{CancelToken as PipeCancel, Hooks};
use fastvideo_cudarc::wan::pipeline::PipelineError;
use fastvideo_cudarc::wan::stream::{CausalRollout, RolloutConfig};
use fastvideo_cudarc::{LoadParts, WanPipeline};
use fastvideo_protocol::{
    ApiError, CanvasCaps, Family, FpsCaps, FrameGrid, KnobCaps, ModelCaps, ModelId, RefLimits,
    ResolvedJob, RgbFrame, StreamCaps, Task,
};

use crate::backend::{
    BlockInput, BlockStats, CausalSpec, ClipOutput, ClipSink, DeviceInfo, EngineBackend,
    LoadEvent, SessionId,
};
use crate::cancel::{cancelled_error, StepControl};
use crate::caps::Recipe;

fn pipe_err(e: PipelineError) -> ApiError {
    if e.is_cancelled() {
        cancelled_error()
    } else {
        ApiError::engine_failed(format!("sf-wan: {e}"))
    }
}

struct Live {
    ro: CausalRollout<'static>,
    prompt: String,
    seed: u64,
    cancel: PipeCancel,
    bridged: bool,
}

/// Causal sessions over one resident SF-Wan pipeline.
pub struct CausalDriver {
    pipe: &'static WanPipeline,
    base: RolloutConfig,
    sessions: HashMap<SessionId, Live>,
}

impl std::fmt::Debug for CausalDriver {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CausalDriver").field("sessions", &self.sessions.len()).finish()
    }
}

impl CausalDriver {
    /// `base` supplies everything but the prompt, canvas and seed (window,
    /// sink, RoPE policy, tokenizer path, text cache).
    pub fn new(pipe: &'static WanPipeline, base: RolloutConfig) -> Self {
        Self {
            pipe,
            base,
            sessions: HashMap::new(),
        }
    }

    pub fn open(&mut self, s: SessionId, spec: &CausalSpec) -> Result<(), ApiError> {
        let cfg = RolloutConfig {
            prompt: spec.prompt.clone(),
            width: spec.width as usize,
            height: spec.height as usize,
            seed: spec.seed,
            rgb8: true,
            ..self.base.clone()
        };
        let ro = CausalRollout::open(self.pipe, cfg).map_err(pipe_err)?;
        self.sessions.insert(
            s,
            Live {
                ro,
                prompt: spec.prompt.clone(),
                seed: spec.seed,
                cancel: PipeCancel::new(),
                bridged: false,
            },
        );
        Ok(())
    }

    pub fn block(
        &mut self,
        s: SessionId,
        input: &BlockInput,
        out: &mut dyn ClipSink,
        ctl: &StepControl,
    ) -> Result<BlockStats, ApiError> {
        let live = self
            .sessions
            .get_mut(&s)
            .ok_or_else(|| ApiError::internal(format!("unknown causal session {s}")))?;
        if !live.bridged {
            // The session's token is the same for every turn: bridge once.
            let flag = live.cancel.flag().clone();
            ctl.cancel.on_cancel(move || flag.store(true, Ordering::Release));
            live.bridged = true;
        }
        if input.reset {
            live.ro.reset(Some(input.seed));
            live.seed = input.seed;
        }
        if input.prompt != live.prompt {
            live.ro.set_prompt(&input.prompt).map_err(pipe_err)?;
            live.prompt = input.prompt.clone();
        }
        let hooks = Hooks::new(Some(&live.cancel), None);
        let b = live.ro.next_block_with_hooks(hooks).map_err(pipe_err)?;
        let first = b.first_frame as u64;
        let total_ms = b.timings.total_s * 1e3;
        let h = b.into_host();
        let (w, hh, n) = (h.width as u32, h.height as u32, h.frames);
        let per = RgbFrame::byte_len(w, hh);
        if h.rgb.len() != per * n {
            return Err(ApiError::engine_failed(format!(
                "sf-wan block has {} RGB bytes for {n} frames of {w}x{hh}",
                h.rgb.len()
            )));
        }
        let frames: Vec<RgbFrame> = h
            .rgb
            .chunks_exact(per)
            .enumerate()
            .map(|(i, px)| RgbFrame {
                width: w,
                height: hh,
                data: px.to_vec().into(),
                index: first + i as u64,
            })
            .collect();
        out.frames(&frames);
        Ok(BlockStats {
            block_index: input.block_index,
            frames: n as u32,
            block_ms: total_ms,
        })
    }

    pub fn close(&mut self, s: SessionId) {
        self.sessions.remove(&s);
    }
}

/// Caps of the SF-Wan 1.3B streaming model: 16 fps, 12-frame blocks,
/// 832×480 default canvas (design §5.4), video only.
pub fn sfwan_caps(id: &str) -> ModelCaps {
    let grid = FrameGrid::new(4, 1, 9, 1_000_001, 81);
    ModelCaps {
        id: ModelId::new(id),
        family: Family::Wan,
        served_names: vec![id.to_owned()],
        tasks: [Task::T2V].into_iter().collect(),
        audio: None,
        fps: FpsCaps::fixed(16),
        stream: Some(StreamCaps::Causal {
            block_frames: 12,
            target_fps: 16,
        }),
        frames: grid,
        canvas: CanvasCaps {
            multiple: 16,
            max_area: 832 * 480,
            aspect: (0.25, 4.0),
            short_edges: vec![480],
            pad_and_crop: false,
            hd: None,
        },
        refs: RefLimits::none(),
        knobs: KnobCaps {
            seed: true,
            ..KnobCaps::default()
        },
        resident: true,
        tier: None,
        recipe: Some("sf-wan-causal-dmd-4step".into()),
    }
}

/// A backend serving only causal SF-Wan (streaming; no batch jobs).
pub struct CausalCudaBackend {
    id: String,
    weights: PathBuf,
    preset: String,
    device: String,
    base: RolloutConfig,
    driver: Option<CausalDriver>,
}

impl std::fmt::Debug for CausalCudaBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CausalCudaBackend")
            .field("id", &self.id)
            .field("weights", &self.weights)
            .finish()
    }
}

impl CausalCudaBackend {
    /// `weights`: the Diffusers root (`transformer/`, `vae/`, `text_encoder/`,
    /// `tokenizer/`); TAEHV from `FASTVIDEO_TAEHV_WEIGHTS` / `FASTVIDEO_TAE_DIR`.
    pub fn new(id: &str, weights: PathBuf, preset: &str, device: &str) -> Self {
        let tok = weights.join("tokenizer").join("tokenizer.json");
        Self {
            id: id.to_owned(),
            base: RolloutConfig {
                tokenizer_path: tok.is_file().then(|| tok.to_string_lossy().into_owned()),
                ..RolloutConfig::default()
            },
            weights,
            preset: preset.to_owned(),
            device: device.to_owned(),
            driver: None,
        }
    }

    /// From `FV_SFWAN_WEIGHTS` (required), `FV_SFWAN_MODEL` (default
    /// `sf-wan`), `FV_SFWAN_PRESET` (`sf_wan_t2v_1_3b`), `FV_CUDA_DEVICE`
    /// (`cuda:0`). `None` when `FV_SFWAN_WEIGHTS` is unset.
    pub fn from_env() -> Option<Self> {
        let w = std::env::var("FV_SFWAN_WEIGHTS").ok().filter(|s| !s.is_empty())?;
        let id = std::env::var("FV_SFWAN_MODEL").unwrap_or_else(|_| "sf-wan".into());
        let preset = std::env::var("FV_SFWAN_PRESET").unwrap_or_else(|_| "sf_wan_t2v_1_3b".into());
        let dev = std::env::var("FV_CUDA_DEVICE").unwrap_or_else(|_| "cuda:0".into());
        Some(Self::new(&id, PathBuf::from(w), &preset, &dev))
    }

    fn driver(&mut self) -> Result<&mut CausalDriver, ApiError> {
        self.driver
            .as_mut()
            .ok_or_else(|| ApiError::engine_failed(format!("`{}` is not loaded", self.id)))
    }
}

impl EngineBackend for CausalCudaBackend {
    fn device(&self) -> DeviceInfo {
        DeviceInfo {
            index: self
                .device
                .rsplit(':')
                .next()
                .and_then(|x| x.parse().ok())
                .unwrap_or(0),
            name: self.device.clone(),
            total_memory_mb: 0,
        }
    }

    fn caps(&self) -> Vec<ModelCaps> {
        vec![sfwan_caps(&self.id)]
    }

    fn recipe(&self, _model: &ModelId) -> Recipe {
        Recipe {
            name: "sf-wan-causal-dmd-4step".into(),
            profile: None,
            steps: Some(4),
            attention: "dense".into(),
            vae: "taehv".into(),
            summary: "Self-Forcing Wan 2.1 1.3B, causal DMD 4 steps, rolling KV (sink 15), TAEHV per block".into(),
        }
    }

    fn load(&mut self, model: &ModelId, obs: &mut dyn FnMut(LoadEvent)) -> Result<(), ApiError> {
        if model.as_str() != self.id {
            return Err(ApiError::invalid_param("model", format!("`{model}` is not served here")));
        }
        if self.driver.is_some() {
            return Ok(());
        }
        obs(LoadEvent::Stage("device"));
        fastvideo_cudarc::resolve_device(&self.device)
            .map_err(|e| ApiError::engine_failed(format!("device {}: {e}", self.device)))?;
        obs(LoadEvent::Stage("pipeline"));
        let pipe = WanPipeline::load_with(&self.weights, &self.preset, LoadParts { text_encoder: true })
            .map_err(|e| ApiError::engine_failed(format!("loading {}: {e}", self.weights.display())))?;
        if pipe.taehv().is_none() {
            return Err(ApiError::engine_failed(
                "SF-Wan streaming decodes with TAEHV (taew2_1): set FASTVIDEO_TAE_DIR or FASTVIDEO_TAEHV_WEIGHTS",
            ));
        }
        let pipe: &'static WanPipeline = Box::leak(Box::new(pipe));
        self.driver = Some(CausalDriver::new(pipe, self.base.clone()));
        Ok(())
    }

    fn generate(&mut self, job: &ResolvedJob, _out: &mut dyn ClipSink, _ctl: &StepControl) -> Result<ClipOutput, ApiError> {
        Err(ApiError::invalid_param(
            "model",
            format!("`{}` serves streaming sessions only (no batch jobs)", job.model),
        ))
    }

    fn causal_open(&mut self, s: SessionId, spec: &CausalSpec) -> Result<(), ApiError> {
        self.driver()?.open(s, spec)
    }

    fn causal_block(
        &mut self,
        s: SessionId,
        input: &BlockInput,
        out: &mut dyn ClipSink,
        ctl: &StepControl,
    ) -> Result<BlockStats, ApiError> {
        self.driver()?.block(s, input, out, ctl)
    }

    fn causal_close(&mut self, s: SessionId) {
        if let Some(d) = self.driver.as_mut() {
            d.close(s);
        }
    }
}
