// Generated by control/gen-configs.mjs from docker/gpucheck.Dockerfile and
// configs/serve: do not edit; run `node gen-configs.mjs`. Which worker configs
// each per-variant serve image carries under /etc/fv, its baked FV_CONFIG, and
// their TOML (what an endpoint serves, derived before a worker boots).
export const IMAGE_CONFIGS: Record<string, { default: string; files: string[] }> = {
  "h3-turbo": {
    "default": "/etc/fv/runpod.toml",
    "files": [
      "runpod.toml",
      "runpod-fake.toml"
    ]
  },
  "h3-max": {
    "default": "/etc/fv/runpod-h3-max.toml",
    "files": [
      "runpod-h3-max.toml",
      "runpod-fake.toml"
    ]
  },
  "ltx": {
    "default": "/etc/fv/runpod-ltx.toml",
    "files": [
      "runpod-ltx.toml",
      "runpod-fake.toml"
    ]
  },
  "wan": {
    "default": "/etc/fv/runpod-wan.toml",
    "files": [
      "runpod-wan.toml",
      "runpod-fake.toml"
    ]
  },
  "wan5b": {
    "default": "/etc/fv/runpod-wan5b.toml",
    "files": [
      "runpod-wan5b.toml",
      "runpod-wan14b.toml",
      "runpod-fake.toml"
    ]
  },
  "sfwan": {
    "default": "/etc/fv/runpod-sfwan.toml",
    "files": [
      "runpod-sfwan.toml",
      "runpod-fake.toml"
    ]
  },
  "cpu": {
    "default": "/etc/fv/runpod-fake.toml",
    "files": [
      "runpod-fake.toml"
    ]
  }
};

export const BAKED_CONFIGS: Record<string, string> = {
  "runpod-fake.toml": `# fv-serve deploy smoke config (WP-16): the fake engine on a real Runpod or
# Vast box, with the production stores (D1 jobs + R2 media when the FV_CF_* /
# FV_R2_* secrets are mapped, design §0 decision 7). Used by
# scripts/serve/{runpod-pod,runpod-endpoint,vast}.sh until the CUDA backend
# (WP-11) serves real models; switch to runpod.toml (engine.backend = cuda)
# then.
#
# State lives on the container disk (/fvstate): the weight volume is never
# written.

[server]
bind = "0.0.0.0:8000"
state_dir = "/fvstate"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "fake"
# The fake engine's post-processing crops encode on the GPU like production.
post_encoder = "nvenc"

[engine.fake]
step_ms = 20
load_ms = 500
all_resident = true
placeholder_output = true

[aliases]
"MiniMax-H3" = "fake-h3-turbo"
"MiniMax-H3-Max" = "fake-h3-max"
"MiniMax-H3-Turbo" = "fake-h3-turbo"
"fastwan-1.3b" = "fake-wan"

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = false
ltx = true
reactor = false
native = true

[limits]
queue_max = 32
body_max_mb = 64
`,
  "runpod-h3-max.toml": `# fv-serve on Runpod: h3-max (Sol-H3 tau ladder). Secrets as in runpod.toml.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# h3-max: Sol-H3 4-step on the tau-ladder engine route (one GPU).
[[models]]
id = "sol-h3"
family = "h3"
recipe = "h3-max"
weights = "\${FV_WEIGHTS}/h3-base"
resident = true
# Image-to-video text: keep the Qwen-VL vision tower resident beside the
# resident text encoder (\`auto\`: when it fits; \`stream\` reads it from the
# volume per request, same bytes). \`warmup\` runs one I2V + one T2V job so
# later requests pay no setup: in the background after readiness (the pod
# takes jobs once the weights are resident; a job cancels the warm-up run in
# flight at its next step and runs first). \`warmup = "blocking"\` (or
# FV_WARMUP=blocking) warms up before readiness instead, as before 2026-10-07.
i2v_encoder = "auto"
warmup = true
# The native 1080P tier is on (80 GB-class GPUs and up): see runpod.toml.
# h3_1080p = false

[aliases]
"MiniMax-H3-Max" = "sol-h3"

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = false
reactor = true
native = true

[limits]
queue_max = 32
body_max_mb = 64

# As an fv-control cluster worker (docs/serve/edge-control-plane.md):
# FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN (the edge's) and FV_DISPATCH_FRONT=1
# make it an API front behind the edge Worker; it registers in \`gw_workers\`
# under \`gateway.pool\`. Standalone deployments ignore this.
[gateway]
pool = "h3-max"
`,
  "runpod-ltx.toml": `# fv-serve on Runpod: LTX-2.5 (ltx-turbo). Secrets as in runpod.toml.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# ltx-turbo: LTX-2.5 distilled two-stage, Sol stage 2 (one GPU).
[[models]]
id = "ltx25-distill-sol"
family = "ltx2"
recipe = "ltx-turbo"
weights = "\${FV_WEIGHTS}/ltx25"
resident = true

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = true
reactor = true
native = true
# fal apps: the default minimax/h3-* apps have no model on this pod. fal's
# own \`lightricks/ltx-2.5\` app serves \`{text,image,audio}-to-video/fast\` here
# (ltx-turbo); its \`/pro\` endpoints need ltx-pro (404 on this pod), as do
# \`fal-ai/ltx-2.3\`'s \`retake-video\` and \`extend-video\` (FV_LTX_RECIPE=ltx-pro).
fal_apps = ["fastvideo/ltx-turbo", "lightricks/ltx-2.5", "fal-ai/ltx-2.3"]

[limits]
queue_max = 32
body_max_mb = 64

# As an fv-control cluster worker (docs/serve/edge-control-plane.md):
# FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN (the edge's) and FV_DISPATCH_FRONT=1
# make it an API front behind the edge Worker; it registers in \`gw_workers\`
# under \`gateway.pool\`. Standalone deployments ignore this.
[gateway]
pool = "ltx"
`,
  "runpod-sfwan.toml": `# fv-serve on a Runpod pod: SF-Wan causal streaming (the \`sfwan\` pool
# preset of fv-control, docs/control/README.md). Secrets as in
# runpod.toml. Peer WebRTC sessions (Reactor, native streams) need inbound
# ICE-TCP/UDP, so this pool runs on pods, not serverless workers.
#
# As an fv-control cluster worker (docs/serve/edge-control-plane.md):
# FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN (the edge's) and FV_DISPATCH_FRONT=1
# make it an API front behind the edge Worker; it registers in \`gw_workers\`
# under \`gateway.pool\`. Standalone deployments ignore this.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900
heartbeat_s = 10

[engine]
backend = "cuda"
post_encoder = "auto"

# SF-Wan 1.3B causal rollout (StreamCaps::Causal), one session per GPU.
[[models]]
id = "sfwan21-1.3b"
family = "wan"
recipe = "sfwan21-1.3b"
weights = "\${FV_WEIGHTS}/sfwan21-1.3b"
resident = true

[protocols]
openai_videos = false
fastwan = false
minimax = false
fal = false
fal_director = false
ltx = false
reactor = true
native = true

[reactor]
model = "sfwan21-1.3b"

# Live causal session length in video seconds (design §5.2, the R12 study):
# requests may ask for up to the hard ceiling; a reset restarts the clock.
[streams]
causal_default_max_s = 120
causal_hard_max_s = 300

[limits]
queue_max = 8
body_max_mb = 64

[gateway]
pool = "sfwan-live"
`,
  "runpod-wan.toml": `# fv-serve on Runpod: FastWan2.1 1.3B. Secrets as in runpod.toml. (The Wan
# tiers are the 5B models: runpod-wan5b.toml.)

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# FastWan2.1 1.3B DMD 3-step, VSA (one GPU; small, add more FASTVIDEO_VSA=1
# Wan models here). Untiered since the 5B FastWan2.2 became wan-turbo.
[[models]]
id = "fastwan21-1.3b"
family = "wan"
recipe = "fastwan21-1.3b"
weights = "\${FV_WEIGHTS}/fastwan21-1.3b"
resident = true

[protocols]
# fal queue app for this model (the default apps are the H3 tiers); tested
# in the GPU E2E (docs/serve/e2e/wan.md).
fal_apps = ["fastvideo/fastwan21-1.3b"]
openai_videos = true
fastwan = true
minimax = true
fal = true
fal_director = true
ltx = false
reactor = true
native = true

[limits]
queue_max = 32
body_max_mb = 64

# As an fv-control cluster worker (docs/serve/edge-control-plane.md):
# FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN (the edge's) and FV_DISPATCH_FRONT=1
# make it an API front behind the edge Worker; it registers in \`gw_workers\`
# under \`gateway.pool\`. Standalone deployments ignore this.
[gateway]
pool = "wan"
`,
  "runpod-wan14b.toml": `# fv-serve on Runpod: the Wan 2.1 T2V-14B fast tier, \`wan14b-turbo\`
# (catalog id \`wan14b-plug-4step\`; docs/serve/research-longlive.md §12).
# Secrets as in runpod.toml.
#
# Wan 2.1 T2V-14B with the LongLive-Plug 14B adapters (few-step lightx2v at
# 1.0 + CFG at 0.5, Apache-2.0) merged into the transformer at load, then the
# LightX2V step-distill Euler sampler: 4 forwards (timesteps 1000 / 750 / 500
# / 250 at shift 5), no CFG. 832x480 (or 480x832), up to 81 frames at 16 fps,
# text-to-video only. RTX PRO 6000: 19.0 s denoise / 22.0 s end to end, 25x
# the base 14B's 100-forward UniPC; about 51 GB peak; the load reads the
# 14B transformer and merges the adapters on the host (~5 min).
#
# Weights (both Runpod volumes, scripts/gpu/weights-manifest.tsv):
#   \${FV_WEIGHTS}/wan21-t2v-14b                          base, Wan-AI/Wan2.1-T2V-14B-Diffusers
#   \${FV_WEIGHTS}/longlive-plug/wan21-t2v-14b-few-step   generator_lora_lightx2v.safetensors
#   \${FV_WEIGHTS}/longlive-plug/wan21-t2v-14b-cfg        adapter_model.safetensors
# The adapters resolve beside the base (\`<weights>/../longlive-plug\`);
# FASTVIDEO_PLUG_ROOT overrides the directory.
#
# Public names: \`wan14b-turbo\` and \`wan14b-plug-4step\` on /fv/v1/jobs and
# /v1/videos; fal queue app \`fastvideo/wan14b-turbo\` (H3-schema app on this
# model, as \`fastvideo/fastwan21-1.3b\` for the 1.3B: 480P, 5 s).

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

[[models]]
id = "wan14b-plug-4step"
family = "wan"
recipe = "wan14b-turbo"
weights = "\${FV_WEIGHTS}/wan21-t2v-14b"
resident = true

[protocols]
fal_apps = ["fastvideo/wan14b-turbo"]
openai_videos = true
fastwan = false
minimax = false
fal = true
fal_director = false
ltx = false
reactor = false
native = true

[limits]
queue_max = 32
body_max_mb = 64

# As a cluster worker (FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN): its pool.
# Standalone deployments ignore this.
[gateway]
pool = "wan14b"
watch_poll_ms = 1000
`,
  "runpod-wan5b.toml": `# fv-serve on Runpod: the Wan 2.2 5B tiers behind fal's \`fal-ai/wan\` app
# (docs/serve/fal-parity.md §3). Secrets as in runpod.toml.
#
#   fal-ai/wan/v2.2-5b/text-to-video            wan-max   (Wan2.2 TI2V-5B, UniPC)
#   fal-ai/wan/v2.2-5b/image-to-video           wan-max
#   fal-ai/wan/v2.2-5b/text-to-video/fast-wan   wan-turbo (FastWan2.2 TI2V-5B, DMD 3-step)
#
# Both run without VSA, so one process serves them. The turbo tier stays
# resident; the max tier loads on demand (\`swap\`): two resident 5B models
# with their f32 UMT5 encoders plus a 704x1280 full-VAE decode do not fit
# 96 GB together.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"
swap = true

[[models]]
id = "fastwan22-ti2v-5b"
family = "wan"
recipe = "wan-turbo"
weights = "\${FV_WEIGHTS}/fastwan22-ti2v-5b"
resident = true

[[models]]
id = "wan22-ti2v-5b"
family = "wan"
recipe = "wan-max"
weights = "\${FV_WEIGHTS}/wan22-ti2v-5b"
resident = false

[protocols]
fal_apps = ["fal-ai/wan"]
openai_videos = true
fastwan = false
minimax = false
fal = true
fal_director = false
ltx = false
reactor = false
native = true

[limits]
queue_max = 32
body_max_mb = 64
`,
  "runpod.toml": `# fv-serve on Runpod (pod, or serverless load balancer with PORT set).
#
# Secrets come from the environment only (design §6.3). The Runpod template
# maps the account secrets (lower-case names) to the upper-case variables
# fv-serve reads:
#
#   FV_CF_ACCOUNT_ID        = {{ RUNPOD_SECRET_fv_cf_account_id }}
#   FV_CF_API_TOKEN         = {{ RUNPOD_SECRET_fv_cf_api_token }}
#   FV_D1_DATABASE_ID       = {{ RUNPOD_SECRET_fv_d1_database_id }}
#   FV_R2_BUCKET            = {{ RUNPOD_SECRET_fv_r2_bucket }}
#   FV_R2_ENDPOINT          = {{ RUNPOD_SECRET_fv_r2_endpoint }}
#   FV_R2_ACCESS_KEY_ID     = {{ RUNPOD_SECRET_fv_r2_access_key_id }}
#   FV_R2_SECRET_ACCESS_KEY = {{ RUNPOD_SECRET_fv_r2_secret_access_key }}
#   FV_API_KEYS, FV_URL_SIGNING_KEY, FV_WEBHOOK_ED25519_KEY (same pattern)
#
# With those set, \`auto\` selects the D1 job store and R2 artifacts.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# One GPU (RTX PRO 6000, 96 GB): the resident models load before /ping
# answers 200. Each entry resolves against the CUDA catalog
# (crates/fastvideo-engine-service/src/cuda/caps.rs): \`recipe\` is a tier alias
# (h3-turbo, h3-max, ltx-turbo, wan-turbo, ...), a catalog id or an H3 recipe
# name; \`weights\` replaces the catalog's weight directory. One H3 DiT is
# ~41 GB, so h3-turbo and h3-max do not co-reside: serve them from separate
# processes (runpod-h3-max.toml), or mark one \`resident = false\` with
# \`[engine] swap = true\` (a switch reloads from the volume).
[[models]]
id = "fasth3"
family = "h3"
recipe = "h3-turbo"
weights = "\${FV_WEIGHTS}/h3-base"
resident = true
served_names = ["fasth3"]
continuity = "anchor-last-frame"
# Image-to-video text: keep the Qwen-VL vision tower resident beside the
# resident text encoder (\`auto\`: when it fits; \`stream\` reads it from the
# volume per request, same bytes). \`warmup\` runs one I2V + one T2V job so
# later requests pay no setup: in the background after readiness (the pod
# takes jobs once the weights are resident; a job cancels the warm-up run in
# flight at its next step and runs first). \`warmup = "blocking"\` (or
# FV_WARMUP=blocking) warms up before readiness instead, as before 2026-10-07.
i2v_encoder = "auto"
warmup = true
# The native 1080P tier (fal \`resolution: "1080P"\`, native \`short_edge: 1080\`
# or \`size: "1920x1080"\`; generated at 1920x1088, cropped to 1080, about 2.5x
# the time of 768P): offered by h3-turbo and h3-max when the GPU passes the
# tier's memory plan (80 GB-class cards and up). 768P stays the default.
# \`h3_1080p = false\` turns it off. docs/serve/h3-1080p-and-upscaler.md.
# h3_1080p = false

[aliases]
"MiniMax-H3" = "fasth3"
"MiniMax-H3-Turbo" = "fasth3"

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = false
reactor = true
native = true

[limits]
queue_max = 32
body_max_mb = 64

# As an fv-control cluster worker (docs/serve/edge-control-plane.md):
# FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN (the edge's) and FV_DISPATCH_FRONT=1
# make it an API front behind the edge Worker; it registers in \`gw_workers\`
# under \`gateway.pool\`. Standalone deployments ignore this.
[gateway]
pool = "h3-turbo"
`,
};
