// Generated by control/gen-configs.mjs from configs/serve: do not edit; edit
// the TOML and run `node gen-configs.mjs`. The pool presets
// (src/cluster/spec.ts) send these inline (FV_WORKER_TOML_B64).
export const WORKER_CONFIGS: Record<string, string> = {
  "runpod-ltx-pro.toml": `# fv-serve on Runpod: LTX-2.5 ltx-pro (the dense two-stage, \`ltx25-distill-dense\`).
# Secrets as in runpod.toml.
#
# SageAttention2 (INT8 QK / FP8 PV) is on by default for this recipe on
# sm_120 (RTX PRO 6000, RTX 5090) only, the one recipe that passed the
# end-to-end gate (docs/perf/sage-attention.md); FASTVIDEO_ATTN_SAGE=0 turns
# it off, =2 forces it on every sm_89+ device (fv-control: a pool env var).
# Its audio-to-video and reference-to-video companions are separate pods
# (runpod-ltx-a2v.toml, runpod-ltx-ref2v.toml).

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# ltx-pro: LTX-2.5 distilled two-stage, dense stage 2 (one GPU).
[[models]]
id = "ltx25-distill-dense"
family = "ltx2"
recipe = "ltx-pro"
weights = "\${FV_WEIGHTS}/ltx25"
resident = true

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = true
reactor = true
native = true
# fal apps: \`lightricks/ltx-2.5\`'s \`/pro\` endpoints and \`fal-ai/ltx-2.3\`
# (its pro tier, \`retake-video\` and \`extend-video\`) run on ltx-pro.
fal_apps = ["lightricks/ltx-2.5", "fal-ai/ltx-2.3"]

[limits]
queue_max = 32
body_max_mb = 64

# Behind the gateway (docs/serve/gateway.md): FV_SERVE_ROLE=worker and
# FV_INTERNAL_TOKEN (the gateway's value); see runpod-ltx.toml.
[gateway]
pool = "ltx-pro"
`,
  "runpod-ltx-a2v.toml": `# fv-serve on Runpod: LTX-2.5 guided audio-to-video (A2VidPipelineTwoStage on
# the dev transformer, docs/oracle.md "LTX-2.5 guided audio-to-video").
# Secrets as in runpod.toml.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# The A2V companion of ltx-pro alone: the LTX-2.5 dev DiT
# (weights/ltx25-dev/transformer_full on both volumes) with the multimodal
# guider at stage 1 (30 steps, CFG 3 = fal \`guidance_scale\`, STG on block 28,
# modality 3, rescale 0.7) and the distilled LoRA fused at stage 2. It serves
# audio-to-video only; \`ltx-pro\` resolves to it on this pod (beside
# ltx25-distill-dense, \`ltx-pro\` A2V routes here). One device copy of the DiT
# (the unfused base in pinned host memory, ~38 GB of host RAM) plus the LoRA
# factors: an 80-96 GB card.
[[models]]
id = "ltx25-a2v-guided"
family = "ltx2"
recipe = "ltx25-a2v-guided"
weights = "\${FV_WEIGHTS}/ltx25"
resident = true
# The dev DiT is \${FV_WEIGHTS}/ltx25-dev/transformer_full (the catalog's
# layout); \`dit = "/abs/path"\` overrides it.

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = true
reactor = true
native = true
# fal apps: \`lightricks/ltx-2.5/audio-to-video/pro\` runs on ltx-pro, i.e.
# this model (\`audio-to-video/fast\` is the ltx-turbo pod's).
fal_apps = ["lightricks/ltx-2.5"]

[limits]
queue_max = 32
body_max_mb = 64

# Behind the gateway (docs/serve/gateway.md): set FV_SERVE_ROLE=worker and
# FV_INTERNAL_TOKEN (the gateway's value) on the template. The worker then
# requires the internal token on every API route, trusts the gateway's
# authentication, and takes jobs from \`/fv/v1/internal/jobs\` (queue: the
# gateway's \`kind: http\` envelope). Standalone deployments ignore this.
[gateway]
pool = "ltx-a2v"
`,
  "runpod-ltx-ref2v.toml": `# fv-serve on Runpod: LTX-2.5 reference-to-video (the Ingredients IC-LoRA,
# docs/ports/ltx-ref2v.md). Secrets as in runpod.toml.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"

# The Ref2V companion of ltx-pro alone: the dense two-stage with the
# Ingredients IC-LoRA fused at stage 1 (weights/ltx25-ic-lora-ingredients on
# both volumes). It serves reference-to-video only; \`ltx-pro\` resolves to it
# on this pod. The DiT keeps an unfused copy of the weights the LoRA touches
# (~26 GB): an 80-96 GB card.
[[models]]
id = "ltx25-ref2v"
family = "ltx2"
recipe = "ltx25-ref2v"
weights = "\${FV_WEIGHTS}/ltx25"
resident = true
# The IC-LoRA is \${FV_WEIGHTS}/ltx25-ic-lora-ingredients/<file> (the catalog's
# layout); \`ic_lora = "/abs/path.safetensors"\` overrides it.

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = true
ltx = true
reactor = true
native = true
# fal apps: fal's \`fal-ai/ltx-2.3-quality/ingredient\` (reference sheet) runs
# on ltx-pro, i.e. this model.
fal_apps = ["fal-ai/ltx-2.3-quality"]

[limits]
queue_max = 32
body_max_mb = 64

# Behind the gateway (docs/serve/gateway.md): set FV_SERVE_ROLE=worker and
# FV_INTERNAL_TOKEN (the gateway's value) on the template. The worker then
# requires the internal token on every API route, trusts the gateway's
# authentication, and takes jobs from \`/fv/v1/internal/jobs\` (queue: the
# gateway's \`kind: http\` envelope). Standalone deployments ignore this.
[gateway]
pool = "ltx-ref2v"
`,
  "runpod-h3-ref2v.toml": `# fv-serve on Runpod: H3 reference-to-video (docs/ports/h3-ref2v.md).
# Secrets as in runpod.toml. Weights: $FV_WEIGHTS/h3-base (text encoder,
# VAEs) and $FV_WEIGHTS/h3-ref2va (transformer_ref + the lightx2v turbo LoRA).
#
# The Ref2VA DiT is a second full 66 GB DiT, so on a 96 GB card (RTX PRO
# 6000) or an 80 GB H100 this is its own process / pool beside the T2V/I2V
# one (runpod-h3-max.toml, runpod.toml); a gateway sends \`reference-to-video\`
# here. On a 141-180 GB card the companions can join the T2V/I2V process
# instead (same [[models]] entries): Ref2V requests on \`h3-max\` / \`h3-turbo\`
# route to them (fastvideo_protocol::route_task).
#
# Turbo (Sol-H3 Ref2VA, 4 forwards) stays resident; max (base Ref2VA, 49
# forwards) is loaded on demand, swapping the turbo DiT out.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900

[engine]
backend = "cuda"
post_encoder = "auto"
# h3-ref2v-max is not resident: its first request swaps the turbo DiT out.
swap = true

[[models]]
id = "h3-ref2v-turbo"
family = "h3"
recipe = "h3-ref2v-turbo"
weights = "\${FV_WEIGHTS}/h3-base"
resident = true

[[models]]
id = "h3-ref2v-max"
family = "h3"
recipe = "h3-ref2v-max"
weights = "\${FV_WEIGHTS}/h3-base"
resident = false

[aliases]
"MiniMax-H3-Max" = "h3-ref2v-max"
"MiniMax-H3-Turbo" = "h3-ref2v-turbo"

[protocols]
openai_videos = true
fastwan = false
minimax = true
fal = true
fal_director = false
ltx = false
reactor = false
native = true

[limits]
queue_max = 32
body_max_mb = 64
`,
  "runpod-longlive.toml": `# fv-serve on a Runpod pod: LongLive-1.3B causal streaming (the SF-Wan
# engine with the LongLive transformer and its prompt-switch KV re-cache,
# docs/serve/research-longlive.md). Secrets as in runpod.toml.
#
# LICENCE: the LongLive-1.3B weights are NON-COMMERCIAL (HF card
# CC-BY-NC-SA-4.0 / CC-BY-NC 4.0): research and evaluation only.
#
# Weights: \`longlive-1.3b-safetensors\` (converted by
# scripts/gpu/convert-longlive.py) plus SF-Wan's text encoder, tokenizer and
# VAE (\`sfwan21-1.3b\`), both on the network volumes. \`longlive\` is not
# expanded like \`weights\`: it is the absolute path under FV_WEIGHTS
# (/workspace/weights on the pods). The [[models]]-less SF-Wan backend reads
# FV_LONGLIVE_WEIGHTS instead (docs/serve/director-causal.md).
#
# Behind the gateway: FV_SERVE_ROLE=worker, FV_INTERNAL_TOKEN, and
# FV_PUBLIC_BASE_URL as in runpod-sfwan.toml.

[server]
bind = "0.0.0.0:8000"
state_dir = "/workspace/fv-state"
shutdown_grace_s = 25

[auth]
mode = "keys"

[artifacts]
backend = "auto"
url_ttl_s = 86400

[jobs]
backend = "auto"
progress_interval_ms = 1000
stale_after_s = 900
heartbeat_s = 10

[engine]
backend = "cuda"
post_encoder = "auto"

# LongLive-1.3B: window 12, sink 3, KV re-cache at prompt switches
# (\`longlive_recache = false\`: keep the cache, the ablation). Served as
# \`longlive-1.3b\` and \`longlive\`.
[[models]]
id = "longlive-1.3b"
family = "wan"
recipe = "sfwan21-1.3b"
weights = "\${FV_WEIGHTS}/sfwan21-1.3b"
resident = true
longlive = "/workspace/weights/longlive-1.3b-safetensors"

[protocols]
openai_videos = false
fastwan = false
minimax = false
fal = false
fal_director = false
ltx = false
reactor = true
native = true

[reactor]
model = "longlive-1.3b"

[streams]
causal_default_max_s = 120
causal_hard_max_s = 300

[limits]
queue_max = 8
body_max_mb = 64

[gateway]
pool = "longlive"
`,
};
