// This file is @generated by prost-build.
/// Payload of a failed response, correlated to its request by request_id.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Framing shared by every channel message. A request expects a correlated
/// response (matched by request_id); a notification is fire-and-forget.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageKind {
    Unspecified = 0,
    Request = 1,
    Response = 2,
    Notification = 3,
}
impl MessageKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_KIND_UNSPECIFIED",
            Self::Request => "MESSAGE_KIND_REQUEST",
            Self::Response => "MESSAGE_KIND_RESPONSE",
            Self::Notification => "MESSAGE_KIND_NOTIFICATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_KIND_REQUEST" => Some(Self::Request),
            "MESSAGE_KIND_RESPONSE" => Some(Self::Response),
            "MESSAGE_KIND_NOTIFICATION" => Some(Self::Notification),
            _ => None,
        }
    }
}
/// Liveness heartbeat from the client.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {}
/// Request for the model's schema.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSchema {}
/// The model's schema, carried as an OpenAPI document.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelSchema {
    #[prost(message, optional, tag = "1")]
    pub openapi: ::core::option::Option<::prost_types::Struct>,
}
/// Notification that a client upload completed and can now be referenced.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileUploaded {
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size: i64,
}
/// Request a clip of the last duration_seconds of output.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RequestClip {
    #[prost(double, tag = "1")]
    pub duration_seconds: f64,
}
/// Request a recording of the session so far.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestRecording {}
/// A clip or recording is being prepared.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClipReady {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub start_marker: f64,
    #[prost(double, tag = "4")]
    pub end_marker: f64,
    #[prost(double, tag = "5")]
    pub now_marker: f64,
    #[prost(int64, tag = "6")]
    pub predicted_ready_at_ms: i64,
    #[prost(string, tag = "7")]
    pub playlist_url: ::prost::alloc::string::String,
}
/// A clip or recording request failed.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClipFailed {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
/// A content-moderation verdict delivered to the client. A "terminate" action
/// means the session is about to end; "warn" is informational and the session
/// continues. Fields the sender cannot attribute are left empty.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Moderation {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub input_kind: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
/// The platform is ending the session, and this is why. Sent best-effort
/// before the connections close, so the client sees the reason rather than a
/// bare disconnect. `reason` is the platform-authored, human-readable
/// description of the cause, delivered verbatim for the client to display.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionEnded {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
/// Request to claim the single publisher slot for an input track.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublishTrack {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Stop sending an input track without releasing the publisher slot.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseTrack {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Resume a paused input track.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeTrack {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Release the publisher slot for an input track.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnpublishTrack {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Successful response to a PublishTrack request. A failure is carried as an
/// Error in the same response slot instead.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublishTrackResponse {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Control channel, client to runtime. Carries all platform and track traffic.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlClientMessage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "2")]
    pub kind: i32,
    #[prost(
        oneof = "control_client_message::Payload",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 40"
    )]
    pub payload: ::core::option::Option<control_client_message::Payload>,
}
/// Nested message and enum types in `ControlClientMessage`.
pub mod control_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Ping(super::Ping),
        #[prost(message, tag = "11")]
        RequestSchema(super::RequestSchema),
        #[prost(message, tag = "12")]
        FileUploaded(super::FileUploaded),
        #[prost(message, tag = "13")]
        RequestClip(super::RequestClip),
        #[prost(message, tag = "14")]
        RequestRecording(super::RequestRecording),
        #[prost(message, tag = "15")]
        PublishTrack(super::PublishTrack),
        #[prost(message, tag = "16")]
        PauseTrack(super::PauseTrack),
        #[prost(message, tag = "17")]
        ResumeTrack(super::ResumeTrack),
        #[prost(message, tag = "18")]
        UnpublishTrack(super::UnpublishTrack),
        #[prost(message, tag = "40")]
        Error(super::Error),
    }
}
/// Control channel, runtime to client. Carries all platform and track traffic.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlServerMessage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "2")]
    pub kind: i32,
    #[prost(
        oneof = "control_server_message::Payload",
        tags = "10, 11, 12, 13, 14, 15, 40"
    )]
    pub payload: ::core::option::Option<control_server_message::Payload>,
}
/// Nested message and enum types in `ControlServerMessage`.
pub mod control_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        ModelSchema(super::ModelSchema),
        #[prost(message, tag = "11")]
        ClipReady(super::ClipReady),
        #[prost(message, tag = "12")]
        ClipFailed(super::ClipFailed),
        #[prost(message, tag = "13")]
        Moderation(super::Moderation),
        #[prost(message, tag = "14")]
        PublishTrack(super::PublishTrackResponse),
        #[prost(message, tag = "15")]
        SessionEnded(super::SessionEnded),
        #[prost(message, tag = "40")]
        Error(super::Error),
    }
}
/// Reference to a file uploaded out of band via the presigned-URL protocol,
/// injected into a Command argument by parameter name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadReference {
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size: i64,
}
/// A model-defined command from the client. type is the command name; the
/// arguments are a dynamic object so the protocol carries any model's schema
/// without knowing it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<::prost_types::Struct>,
    #[prost(map = "string, message", tag = "3")]
    pub uploads: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        UploadReference,
    >,
}
/// A model-emitted message to the client. type is the message name; the body is
/// a dynamic object.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelMessage {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<::prost_types::Struct>,
}
/// Data channel, client to runtime. Carries only the model's own command
/// traffic; all platform and track messages travel on the control channel.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataClientMessage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "2")]
    pub kind: i32,
    #[prost(oneof = "data_client_message::Payload", tags = "10, 40")]
    pub payload: ::core::option::Option<data_client_message::Payload>,
}
/// Nested message and enum types in `DataClientMessage`.
pub mod data_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Command(super::Command),
        #[prost(message, tag = "40")]
        Error(super::Error),
    }
}
/// Data channel, runtime to client. Carries only the model's own emitted
/// messages.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataServerMessage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "2")]
    pub kind: i32,
    #[prost(oneof = "data_server_message::Payload", tags = "10, 40")]
    pub payload: ::core::option::Option<data_server_message::Payload>,
}
/// Nested message and enum types in `DataServerMessage`.
pub mod data_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Message(super::ModelMessage),
        #[prost(message, tag = "40")]
        Error(super::Error),
    }
}
