// Generates the controller's copies of the serve configs from
// configs/serve (the source of truth):
//   src/cluster/worker-configs.ts   the worker configs the pool presets send
//                                   inline (FV_WORKER_TOML_B64), so they run on
//                                   images whose variant does not carry them
//   src/serverless/console-assets.ts fv-serve's console pages and assets
//                                   (crates/fastvideo-serve/console, the
//                                   files console.rs embeds), served unchanged
//                                   by the serverless console proxy
//   node gen-configs.mjs            rewrite them
//   node gen-configs.mjs --check    exit 1 when they are stale (test/unit/payloads.test.ts runs the same check)
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVE = join(HERE, "../configs/serve");
const CONSOLE = join(HERE, "../crates/fastvideo-serve/console");

/** The worker configs src/cluster/spec.ts's presets send inline. */
export const INLINE_WORKER_CONFIGS = ["runpod-ltx-pro.toml", "runpod-ltx-a2v.toml", "runpod-ltx-ref2v.toml", "runpod-h3-ref2v.toml", "runpod-longlive.toml"];

const lit = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

export function workerConfigsTs() {
  const entries = INLINE_WORKER_CONFIGS.map((n) => `  ${JSON.stringify(n)}: ${lit(readFileSync(join(SERVE, n), "utf8"))},`);
  return `// Generated by control/gen-configs.mjs from configs/serve: do not edit; edit
// the TOML and run \`node gen-configs.mjs\`. The pool presets
// (src/cluster/spec.ts) send these inline (FV_WORKER_TOML_B64).
export const WORKER_CONFIGS: Record<string, string> = {
${entries.join("\n")}
};
`;
}

/** The console's files as console.rs serves them: pages by name (index.html → `/console`), assets with their content type. */
export function consoleAssetsTs() {
  const files = readdirSync(CONSOLE).filter((f) => /\.(html|js|css)$/.test(f)).sort();
  const type = (f) => (f.endsWith(".css") ? "text/css; charset=utf-8" : "text/javascript; charset=utf-8");
  const pages = files.filter((f) => f.endsWith(".html")).map((f) => `  ${JSON.stringify(f.replace(/\.html$/, ""))}: ${lit(readFileSync(join(CONSOLE, f), "utf8"))},`);
  const assets = files.filter((f) => !f.endsWith(".html")).map((f) => `  ${JSON.stringify(f)}: { type: ${JSON.stringify(type(f))}, body: ${lit(readFileSync(join(CONSOLE, f), "utf8"))} },`);
  return `// Generated by control/gen-configs.mjs from crates/fastvideo-serve/console: do
// not edit; edit the console and run \`node gen-configs.mjs\`. The serverless
// console proxy (src/serverless/console.ts) serves these unchanged.
export const CONSOLE_PAGES: Record<string, string> = {
${pages.join("\n")}
};
export const CONSOLE_ASSETS: Record<string, { type: string; body: string }> = {
${assets.join("\n")}
};
`;
}

export const OUTPUTS = { "src/cluster/worker-configs.ts": workerConfigsTs, "src/serverless/console-assets.ts": consoleAssetsTs };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [rel, gen] of Object.entries(OUTPUTS)) {
    const p = join(HERE, rel);
    const want = gen();
    let cur = "";
    try {
      cur = readFileSync(p, "utf8");
    } catch {}
    if (cur === want) continue;
    stale++;
    if (check) console.error(`stale: ${rel} (run: node gen-configs.mjs)`);
    else writeFileSync(p, want), console.log(`wrote ${rel}`);
  }
  if (check && stale) process.exit(1);
}
