// Generates the controller's copies of the serve configs from
// configs/serve (the source of truth):
//   src/cluster/worker-configs.ts   the worker configs the pool presets send
//                                   inline (FV_WORKER_TOML_B64), so they run on
//                                   images whose variant does not carry them
//   src/cluster/image-configs.ts    which configs each per-variant image carries
//                                   (docker/gpucheck.Dockerfile serve-<variant>
//                                   stages), its baked FV_CONFIG, and their TOML
//                                   (what a serverless endpoint serves before a
//                                   worker boots, docs/control/serverless.md)
//   node gen-configs.mjs            rewrite them
//   node gen-configs.mjs --check    exit 1 when they are stale (test/unit/payloads.test.ts runs the same check)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVE = join(HERE, "../configs/serve");

/** The worker configs src/cluster/spec.ts's presets send inline. */
export const INLINE_WORKER_CONFIGS = ["runpod-ltx-pro.toml", "runpod-ltx-a2v.toml", "runpod-ltx-ref2v.toml", "runpod-h3-ref2v.toml", "runpod-longlive.toml"];

const lit = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

export function workerConfigsTs() {
  const entries = INLINE_WORKER_CONFIGS.map((n) => `  ${JSON.stringify(n)}: ${lit(readFileSync(join(SERVE, n), "utf8"))},`);
  return `// Generated by control/gen-configs.mjs from configs/serve: do not edit; edit
// the TOML and run \`node gen-configs.mjs\`. The pool presets
// (src/cluster/spec.ts) send these inline (FV_WORKER_TOML_B64).
export const WORKER_CONFIGS: Record<string, string> = {
${entries.join("\n")}
};
`;
}

/** The per-variant serve images' configs, read from the Dockerfile's serve-<variant> stages. */
export function imageConfigs() {
  const df = readFileSync(join(HERE, "../docker/gpucheck.Dockerfile"), "utf8");
  const out = {};
  let cur = null;
  for (const line of df.split("\n")) {
    const from = /^FROM\s+\S+\s+AS\s+serve-([a-z0-9-]+)\s*$/i.exec(line);
    if (from) {
      cur = ["build", "cuda-bin"].includes(from[1]) ? null : (out[from[1]] = { default: "", files: [] });
      continue;
    }
    if (/^FROM\s/i.test(line)) cur = null;
    if (!cur) continue;
    const cp = /^COPY\s+(.+)\s+\/etc\/fv\/\s*$/.exec(line);
    if (cp) for (const f of cp[1].split(/\s+/)) if (f.startsWith("configs/serve/")) cur.files.push(f.slice("configs/serve/".length));
    const env = /\bFV_CONFIG=(\S+)/.exec(line);
    if (/^ENV\s/.test(line) && env) cur.default = env[1];
  }
  return out;
}

export function imageConfigsTs() {
  const imgs = imageConfigs();
  const files = [...new Set(Object.values(imgs).flatMap((i) => i.files))].sort();
  const entries = files.map((n) => `  ${JSON.stringify(n)}: ${lit(readFileSync(join(SERVE, n), "utf8"))},`);
  return `// Generated by control/gen-configs.mjs from docker/gpucheck.Dockerfile and
// configs/serve: do not edit; run \`node gen-configs.mjs\`. Which worker configs
// each per-variant serve image carries under /etc/fv, its baked FV_CONFIG, and
// their TOML (what an endpoint serves, derived before a worker boots).
export const IMAGE_CONFIGS: Record<string, { default: string; files: string[] }> = ${JSON.stringify(imgs, null, 2)};

export const BAKED_CONFIGS: Record<string, string> = {
${entries.join("\n")}
};
`;
}

export const OUTPUTS = { "src/cluster/worker-configs.ts": workerConfigsTs, "src/cluster/image-configs.ts": imageConfigsTs };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [rel, gen] of Object.entries(OUTPUTS)) {
    const p = join(HERE, rel);
    const want = gen();
    let cur = "";
    try {
      cur = readFileSync(p, "utf8");
    } catch {}
    if (cur === want) continue;
    stale++;
    if (check) console.error(`stale: ${rel} (run: node gen-configs.mjs)`);
    else writeFileSync(p, want), console.log(`wrote ${rel}`);
  }
  if (check && stale) process.exit(1);
}
