// Generates the controller's copies of the serve configs from
// configs/serve (the source of truth):
//   src/cluster/worker-configs.ts   the worker configs the pool presets send
//                                   inline (FV_WORKER_TOML_B64), so they run on
//                                   images whose variant does not carry them
//   node gen-configs.mjs            rewrite them
//   node gen-configs.mjs --check    exit 1 when they are stale (test/unit/payloads.test.ts runs the same check)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVE = join(HERE, "../configs/serve");

/** The worker configs src/cluster/spec.ts's presets send inline. */
export const INLINE_WORKER_CONFIGS = ["runpod-ltx-pro.toml", "runpod-ltx-a2v.toml", "runpod-ltx-ref2v.toml", "runpod-h3-ref2v.toml", "runpod-longlive.toml"];

const lit = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

export function workerConfigsTs() {
  const entries = INLINE_WORKER_CONFIGS.map((n) => `  ${JSON.stringify(n)}: ${lit(readFileSync(join(SERVE, n), "utf8"))},`);
  return `// Generated by control/gen-configs.mjs from configs/serve: do not edit; edit
// the TOML and run \`node gen-configs.mjs\`. The pool presets
// (src/cluster/spec.ts) send these inline (FV_WORKER_TOML_B64).
export const WORKER_CONFIGS: Record<string, string> = {
${entries.join("\n")}
};
`;
}

export const OUTPUTS = { "src/cluster/worker-configs.ts": workerConfigsTs };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [rel, gen] of Object.entries(OUTPUTS)) {
    const p = join(HERE, rel);
    const want = gen();
    let cur = "";
    try {
      cur = readFileSync(p, "utf8");
    } catch {}
    if (cur === want) continue;
    stale++;
    if (check) console.error(`stale: ${rel} (run: node gen-configs.mjs)`);
    else writeFileSync(p, want), console.log(`wrote ${rel}`);
  }
  if (check && stale) process.exit(1);
}
